// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccountTransaction struct {
	TransactionID              pgtype.UUID
	AccountID                  int64
	UserID                     int64
	TransactionName            string
	MagnifiedTransactionAmount int64
	TransactionType            int32
	CategoryID                 int64
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
	Notes                      string
	CreatedBy                  string
}

type AccountTransactionApproval struct {
	ApprovalID                 pgtype.UUID
	AccountID                  int64
	UserID                     int64
	TransactionName            string
	MagnifiedTransactionAmount int64
	TransactionType            int32
	CategoryID                 int64
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
	Notes                      string
	CreatedBy                  string
}

type Category struct {
	CategoryID       int64
	CategoryName     string
	ParentCategoryID pgtype.Int8
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type UserAccount struct {
	AccountID               int64
	UserID                  int64
	AccountName             string
	MagnifiedBalanceSummary int64
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	RollupAt                pgtype.Timestamptz
	Currency                string
}

type UserApiKey struct {
	ApiKeyID      string
	ApiSecretHash string
	Identifier    string
	CreatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

type UserAuth struct {
	UserID       int64
	PasswordHash pgtype.Text
}

type UserDatum struct {
	UserID    int64
	Name      string
	Username  string
	Email     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
